name: ci

on: push

jobs:  
  build:     
   runs-on: ubuntu-latest
   
   steps:    
   - uses: actions/checkout@v1
   - name: Build and test with Docker
     run: |
       docker build -t purbeurre:vtest .
       docker run --env-file .env purbeurre:vtest sh -c "python -m pytest"