name: CI
on: push

jobs:       
  build:
   environment: env
   runs-on: ubuntu-latest

   steps:    
   - uses: actions/checkout@v1
   - name: Build and test with Docker
     run: |
       docker build -t purbeurre:vtest .
       docker run \
        --env PB_SECRET_KEY=${{ secrets.PB_SECRET_KEY }} \
        --env DB_NAME=${{ secrets.DB_NAME }} \
        --env DB_USER=${{ secrets.DB_USER }} \
        --env DB_PWD=${{ secrets.DB_PWD }} \
        --env DB_HOST=${{ secrets.DB_HOST }} \
        --env DB_PORT=${{ secrets.DB_PORT }} \
        --env ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }} \
        --env SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }} \
        --env STATIC_BUCKET_NAME=app-purbeurre \
        --env S3_REGION_NAME=fr-par \
        purbeurre:vtest sh -c "python -m pytest"