name: ci

on: push

jobs:  
  build:
   environment: env
   runs-on: ubuntu-latest
   
   steps:    
   - uses: actions/checkout@v1
   - name: Test code
     run: |
        python -m venv .env
        pip install -r requirements.txt
        .env/scripts/activate
        python -m pytest
